package error_responses

const (
	EMAIL_INVALID = 1
	EMAIL_ALREADY_IN_USE = 2
	PASSWORD_INVALID = 3
	BIRTHDATE_INVALID = 4
	NAME_INVALID = 5
	MISSING_FIELDS = 6
	BODY_INVALID = 7
	DATABASE_ERROR = 8
	USER_NOT_FOUND = 9
	LOGIN_DATA_INVALID = 10
	TOKEN_GENERATION_FAILED = 11
	GENDER_DOES_NOT_EXIST = 12
	UNAUTHORIZED = 13
	MISSING_PERMISSION = 14
	REMINDER_ENTRY_NOT_FOUND = 15
	NOTIFICATION_ALREADY_EXISTS = 16
)